# Neden Numpy?

In [ ]:
import numpy as np

In [21]:
a=np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [22]:
type(a) #ndarray

numpy.ndarray

In [28]:
np.array([3.14,4,2,14],dtype="float32")  #Tek tipte veri tutar

array([ 3.14,  4.  ,  2.  , 14.  ], dtype=float32)

In [ ]:
#sıfırdan array oluşturma

In [29]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.ones((3,4),dtype="float32")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
np.full((12,2),9,dtype="int")

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [36]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [37]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [38]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [39]:
np.random.normal(10,4,(3,4))

array([[ 8.95106485,  8.20098248, 13.13287122, 10.44612824],
       [12.75424649, 12.83726159,  6.23900081,  9.91876501],
       [16.00428693,  9.78243775,  6.41557089,  5.76497475]])

In [40]:
np.random.randint(0,10,(3,4))

array([[5, 8, 5, 6],
       [1, 3, 5, 6],
       [3, 0, 2, 9]])