# Array Ayırma(Splitting)

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,99,99,3,2,1])

In [8]:
a,b,c=np.split(x,[3,5])

In [9]:
a

array([1, 2, 3])

In [10]:
#iki boyutlu ayırma

In [12]:
m=np.arange(16).reshape((4,4))
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
c,f=np.vsplit(m,[2])

In [20]:
d=np.concatenate([c,f],axis=1)
d

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [24]:
sag,sol=np.hsplit(m,[2])

In [25]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [26]:
np.concatenate([sag,sol])

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [27]:
np.concatenate([sol,sag],axis=1)

array([[ 2,  3,  0,  1],
       [ 6,  7,  4,  5],
       [10, 11,  8,  9],
       [14, 15, 12, 13]])

In [ ]:
np.v