# İki bilinmeyenli Denklemleri Çözme


In [1]:
import numpy as np

In [2]:
5*x0+x1=12
x0+3*x1=10

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (764585304.py, line 1)

In [3]:
a=np.array([[5,1],
            [1,3]])
b=np.array([12,10])

In [4]:
a

array([[5, 1],
       [1, 3]])

In [5]:
b

array([12, 10])

In [6]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])