# Index ile Elemanlara Erismek

In [3]:
import numpy as np
a=np.random.randint(3,10,size=10)
a

array([7, 4, 7, 4, 5, 8, 8, 9, 4, 8])

In [4]:
a[0]

7

In [5]:
a[-1]

8

In [6]:
a[0]=100

In [11]:
m=np.random.randint(10,size=(2,5))
m

array([[7, 5, 2, 5, 4],
       [8, 5, 4, 5, 2]])

In [12]:
m[0][1]

5

In [17]:
m[0,0]=3.1

In [18]:
m

array([[3, 5, 2, 5, 4],
       [8, 5, 4, 5, 2]])

# Slicing ile Elemanlara Erişmek(Array Alt Kümesine Erişmek)

In [20]:
z=np.arange(20,30)
z

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
z[1:3]

array([21, 22])

In [24]:
z[::-1]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

In [26]:
#iki boyutlu slice işlemleri

In [28]:
k=np.random.randint(10,size=(5,5))
k

array([[4, 7, 0, 3, 7],
       [6, 5, 1, 7, 8],
       [8, 0, 7, 8, 3],
       [9, 4, 1, 9, 1],
       [0, 3, 6, 3, 1]])

In [29]:
k[:,0]

array([4, 6, 8, 9, 0])

In [34]:
k[0:,0:1]

array([[4],
       [6],
       [8],
       [9],
       [0]])

In [38]:
k[0::3,0::2]

array([[4, 0, 7],
       [9, 1, 1]])

In [39]:
k

array([[4, 7, 0, 3, 7],
       [6, 5, 1, 7, 8],
       [8, 0, 7, 8, 3],
       [9, 4, 1, 9, 1],
       [0, 3, 6, 3, 1]])

In [47]:
alt_k=k[0:3,0:2]
alt_k

array([[999,   7],
       [  6,   5],
       [  8,   0]])

In [46]:
copy_k=np.copy(alt_k)
copy_k

array([[999,   7],
       [  6,   5],
       [  8,   0]])

In [48]:
copy_k[0][0]=3

In [49]:
alt_k

array([[999,   7],
       [  6,   5],
       [  8,   0]])

In [50]:
copy_k

array([[3, 7],
       [6, 5],
       [8, 0]])

In [51]:
k

array([[999,   7,   0,   3,   7],
       [  6,   5,   1,   7,   8],
       [  8,   0,   7,   8,   3],
       [  9,   4,   1,   9,   1],
       [  0,   3,   6,   3,   1]])

In [ ]:
;