# Fancy Index ile Elemanlara Erişmek

In [1]:
import numpy as np
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [2]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [5]:
al_getir=[1,3,5]

In [6]:
v[al_getir]

array([ 3,  9, 15])

In [ ]:
#iki boyutta fancy

In [20]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [25]:
m[satir,sutun]

array([1, 5])

In [ ]:
#basit index ile fancy index

In [28]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
m[0,[1,2]]

array([1, 2])

In [ ]:
#slice ile fancy

In [30]:
m[0:,[1,2]]=   [[99,99],[99,99],[99,99]]

In [31]:
m

array([[ 0, 99, 99],
       [ 3, 99, 99],
       [ 6, 99, 99]])