# Matematiksel İşlemler

In [2]:
import numpy as np
v=np.arange(1,6)
v

array([1, 2, 3, 4, 5])

In [3]:
v-1

array([0, 1, 2, 3, 4])

In [ ]:
#ufunc

In [4]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [5]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [6]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [7]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [8]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [9]:
np.mod(v,3)

array([1, 2, 0, 1, 2], dtype=int32)

In [11]:
np.absolute(np.array([1,2,-3]))

array([1, 2, 3])

In [12]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
#cheatsheet

In [16]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.mean(a) #ortalama

5.0

In [19]:
np.sum(a)

45

In [21]:
np.var(a) #varyans

6.666666666666667

In [22]:
np.std(a) #standart sapma

2.581988897471611