# Array Sıralama(Sorting)

In [1]:
import numpy as np

In [2]:
v=np.array([2,1,4,5,3])

In [3]:
v

array([2, 1, 4, 5, 3])

In [7]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [8]:
v

array([2, 1, 4, 5, 3])

In [10]:
#iki boyutlu array sıralama

In [19]:
ab=np.random.normal(20,5,(3,3))
ab

array([[17.45801177, 22.51406139, 18.26197336],
       [20.38851385, 17.31834152, 19.2198069 ],
       [22.08877782, 16.34985488, 20.95907465]])

In [25]:
ab=np.sort(ab,1)
ab

array([[17.45801177, 18.26197336, 22.51406139],
       [17.31834152, 19.2198069 , 20.38851385],
       [16.34985488, 20.95907465, 22.08877782]])

In [24]:
np.sort(ab,0)

array([[16.34985488, 18.26197336, 20.38851385],
       [17.31834152, 19.2198069 , 22.08877782],
       [17.45801177, 20.95907465, 22.51406139]])